# Copyright © 2023 Horizoncd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.1
info:
  title: Horizon Environment Template Restful
  version: 2.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/core/v2/applications/{applicationID}/envtemplates?envrionment={envrionment}:
    parameters:
      - $ref: 'common.yaml#/components/parameters/paramApplicationID'
      - $ref: 'common.yaml#/components/parameters/queryEnvironment'
    post:
      tags:
        - application
      operationId: updateEnvTemplate
      summary: update a specified env template for an application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                application:
                  $ref: "#/components/schemas/application"
                pipeline:
                  $ref: "#/components/schemas/pipeline"
      responses:
        "200":
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
    get:
      tags:
        - application
      operationId: getEnvTemplate
      summary: get a specified env template for an application
      description: if template for specified env is not exists, return the default template of this application.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: object
                    properties:
                      application:
                        $ref: "#/components/schemas/application"
                      pipeline:
                        $ref: "#/components/schemas/pipeline"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
components:
  schemas:
    application:
      type: object
      description: template config of application
      additionalProperties: true
    pipeline:
      type: object
      description: build config of application
      additionalProperties: true

