# Copyright © 2023 Horizoncd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.1
info:
  title: Horizon-Code-Front
  description: Front API About Terminal
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/front/v1/code/listbranch:
    parameters:
      - name: giturl
        in: query
        description: giturl the the code repo
        required: true
      - name: filter
        in: query
        description: the filter
        required: false
      - name: pageNumber
        in: query
        description: the page number
        required: false
      - name: pageSize
        in: query
        description: the page size of per page
    get:
      tags:
        - code
      operationId: listbranch
      summary: list the branches if git a repo
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
  /apis/front/v1/code/listtag:
    parameters:
      - name: giturl
        in: query
        description: giturl the the code repo
        required: true
      - name: filter
        in: query
        description: the filter
        required: false
      - name: pageNumber
        in: query
        description: the page number
        required: false
      - name: pageSize
        in: query
        description: the page size of per page
    get:
      tags:
        - code
      operationId: listtag
      summary: list the git repo tags
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"