# Copyright © 2023 Horizoncd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.1
info:
  title: Horizon-group-front
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/front/v1/groups?fullPath={fullPath}:
    get:
      tags:
        - group
      operationId: queryGroups
      summary: query group by fullPath
      parameters:
        - name: fullPath
          in: query
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    $ref: "#/components/schemas/GroupChild"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
  /apis/front/v1/groups/authedgroups:
    get:
      tags:
        - group
      operationId: listAuthedGroups
      summary: list all the groups that authed by the current user (group owner\maintainer)
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../restful/group.yaml#/components/schemas/Group"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
  /apis/front/v1/groups/searchgroups?groupID={groupID}&filter={filter}:
    get:
      tags:
        - group
      description: search subGroups of a group
      summary: search subGroups
      operationId: searchGroups
      parameters:
        - name: groupID
          in: query
        - name: filter
          in: query
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GroupChild'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
  /apis/front/v1/groups/searchchildren?groupID={groupID}&filter={filter}:
    get:
      tags:
        - group
      description: search children of a group
      summary: search children
      operationId: searchChildren
      parameters:
        - name: groupID
          in: query
        - name: filter
          in: query
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GroupChild'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
  /apis/front/v1/groups/children?groupID={groupID}&pageNumber=${pageNumber}&pageSize={pageSize}:
    get:
      tags:
        - group
      operationId: queryGroupChildren
      summary: query children of a group
      parameters:
        - name: groupID
          in: query
        - $ref: 'common.yaml#/components/parameters/pageNumber'
        - $ref: 'common.yaml#/components/parameters/pageSize'
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GroupChild'
          description: Success
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
components:
  schemas:
    GroupChild:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        path:
          type: string
        fullName:
          type: string
        fullPath:
          type: string
        type:
          $ref: '#/components/schemas/GroupChildType'
        childrenCount:
          type: integer
        Children:
          type: array
          items:
            $ref: '#/components/schemas/GroupChild'
        parentID:
          type: integer
        createdAt:
          $ref: "../restful/common.yaml#/components/schemas/Date"
        updatedAt:
          $ref: "../restful/common.yaml#/components/schemas/Date"

    GroupChildType:
      type: string
      enum:
        - group
        - application



